# Generated by Django 4.1.7 on 2023-02-16 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_author_alter_book_price_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='authors',
        ),
    ]
